### ISSUE TITLE
Add your details to the Website

### ISSUE THREAD

**Issue by dewanshrawat15** [dsc-bvp-pune/Hacktoberfest#2]
The website has a list of contributors. Add an image with only your first name to the ```assets/contributors/``` folder. Update your name in the section and your photo is live on the website.

**Comment by dewanshrawat15** [comment]
@codetronaut I want to work on this issue

**Comment by thisistusharsh** [comment]
@dewanshrawat15 I want to work on this issue.

**Comment by dewanshrawat15** [comment]
@thisistusharsh please feel free to work on it
